USE AdventureWorks2008 ;
GO
IF (SELECT  OBJECT_ID('dbo.t1')
   ) IS NOT NULL 
    DROP TABLE dbo.t1;
GO
CREATE TABLE dbo.t1 (c1 INT, c2 CHAR(996));
CREATE CLUSTERED INDEX i1 ON dbo.t1 (c1);
INSERT  INTO dbo.t1
VALUES  (1, '1');
INSERT  INTO dbo.t1
VALUES  (2, '2');
GO
