IF(SELECT OBJECT_ID('p1')) IS NOT NULL
  DROP PROC p1
GO
CREATE PROC p1
AS
SELECT 'a' + null + 'b' --1st
SET CONCAT_NULL_YIELDS_NULL OFF
SELECT 'a' + null + 'b' --2nd
SET ANSI_NULLS OFF
SELECT 'a' + null + 'b' --3rd
GO

SET CONCAT_NULL_YIELDS_NULL OFF
SET ANSI_NULLS OFF
EXEC p1
SET CONCAT_NULL_YIELDS_NULL ON --Reset to default
SET ANSI_NULLS ON              --Reset to default
